from datetime import datetime, timedelta, timezone

from cryptography import x509
from cryptography.x509.oid import NameOID, ExtendedKeyUsageOID
from cryptography.hazmat.primitives import hashes, serialization
from fastapi import Request, Response


LEAF_TTL = timedelta(hours=1)  # decision S02


def client_cn_from_mtls(request: Request) -> str | None:
    """Extracts CN from mTLS client certificate via ASGI 'tls' extension (uvicorn 0.27+).

    Works under `uvicorn --ssl-cert-reqs 2 --ssl-ca-certs root.pem`.
    Returns None if extension is not available (fallback in error handling).
    """
    tls_ext = request.scope.get("extensions", {}).get("tls")
    
    ##############################
    print("DEBUG extensions keys:", list(request.scope.get("extensions", {}).keys()))
    print("DEBUG tls_ext type:", type(tls_ext).__name__)
    if isinstance(tls_ext, dict):
        print("DEBUG tls_ext keys:", list(tls_ext.keys()))
        chain = tls_ext.get("client_cert_chain") or []
        print("DEBUG client_cert_chain len:", len(chain))
        if chain:
            first = chain[0]
            if isinstance(first, bytes):
                print("DEBUG chain[0] bytes prefix:", first[:32])
            else:
                print("DEBUG chain[0] type/value prefix:", type(first).__name__, str(first)[:64])
    ##############################
    
    if not tls_ext:
        return None
    # ASGI TLS extension passes DER-encoded client certs as bytes
    chain = tls_ext.get("client_cert_chain") or []
    if not chain:
        return None
    leaf_pem_or_der = chain[0]
    try:
        if isinstance(leaf_pem_or_der, str) or leaf_pem_or_der.startswith(
            b"-----BEGIN"
        ):
            cert = x509.load_pem_x509_certificate(
                leaf_pem_or_der
                if isinstance(leaf_pem_or_der, bytes)
                else leaf_pem_or_der.encode()
            )
        else:
            cert = x509.load_der_x509_certificate(leaf_pem_or_der)
    except ValueError:
        return None
    cns = cert.subject.get_attributes_for_oid(NameOID.COMMON_NAME)
    return cns[0].value if cns else None


def sign_csr(csr: x509.CertificateSigningRequest) -> bytes:
    """Signs the CSR with the intermediate key. Returns the leaf cert in PEM."""
    now = datetime.now(timezone.utc)
    builder = (
        x509.CertificateBuilder()
        .subject_name(csr.subject)
        .issuer_name(INT_CERT.subject)
        .public_key(csr.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + LEAF_TTL)
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=False,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        # MVP: assume serverAuth (the workload is a FastAPI server). Client-only
        # certs (like orch) are still generated by a local script in the MVP.
        # Exposing the certificate type through the API is future work.
        .add_extension(
            x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]), critical=False
        )
        .add_extension(
            x509.SubjectKeyIdentifier.from_public_key(csr.public_key()), critical=False
        )
        .add_extension(
            x509.AuthorityKeyIdentifier.from_issuer_subject_key_identifier(INT_SKI),
            critical=False,
        )
    )
    # SAN: copy from the CSR if present - without SAN, modern clients will reject the cert
    try:
        san = csr.extensions.get_extension_for_class(x509.SubjectAlternativeName).value
        builder = builder.add_extension(san, critical=False)
    except x509.ExtensionNotFound:
        pass
    leaf = builder.sign(INT_KEY, hashes.SHA256())
    return leaf.public_bytes(serialization.Encoding.PEM)
